theme: jekyll-theme-minimal
title: Trent Thomas
description: Astrobiologist and Planetary Scientist
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Research Highlights
    url: research
  - title: Outreach
    url: outreach
  - title: Curriculum Vitae
    url: assets/cvs/tthomas_cv.pdf

