theme: jekyll-theme-minimal
logo: /assets/img/rlolegario_photo.png
title: Raphael L. Olegário
description: PhD Candidate in Medical Sciences at University of Brasília
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Research
    url: research
  - title: Publications and Code
    url: publications
  - title: Outreach
    url: outreach
  - title: Curriculum Vitae
    url: assets/cvs/tthomas_cv.pdf

